### ISSUE TITLE
we lazy af (me)+ cant rly code

### ISSUE THREAD

**Issue by kubali3** [frdomainhostlolveryuniqueusernamesoyea/main#1]
i did nothing and lazy **af** find a fix

**Comment by kubali3** [comment]
damn that bad

**Comment by kubali3** [comment]
also i still dont know how to create folders on github

**Comment by kubali3** [comment]
almost rm rf d the whole page

**Comment by frdhostlolveryuniqueusernamesoyea** [comment]
nice

**Comment by kubali3** [comment]
![trash can](https://github.com/user-attachments/assets/b9c56c70-e3e7-490b-8b10-07364cc67bda)

**Comment by kubali3** [comment]
nice reply

**Comment by kubali3** [comment]
we got brainrotted

**Comment by MrTomiCZ** [comment]
yeah

**Comment by MrTomiCZ** [comment]
je to isue

**Comment by kubali3** [comment]
i sajd klous

**Comment by MrTomiCZ** [comment]
asdkioplju
